# Autogenerated at 2017-04-22T13:36:51.200456 on version 0.0.1
import casingSimulations
import numpy as np

# Set up the simulation
sim = casingSimulations.run.SimulationFDEM(
    cp='CasingParameters.json',
    meshGenerator='MeshParameters.json',
    srcType='TopCasingSrc',
    fields_filename='fields.npy'
)

# run the simulation 
fields = sim.run()
# Set up DC survey for the same source location
csz = sim.meshGenerator.csz
src_a = sim.src.src_a_closest - np.r_[0., 0., csz/2.] # make sure it is in the cell
src_b = sim.src.src_b_closest - np.r_[0., 0., csz/2.] # make sure it is in the cell

simDC = casingSimulations.run.SimulationDC(
    cp='CasingParameters.json',
    meshGenerator='MeshParameters.json',
    src_a=src_a,
    src_b=src_b
)
# run the DC simulation 
fieldsDC = simDC.run()